package com.w1therx.adventurerfantasy.common.enums;


public enum StatType {
    ADDITIONAL_JUMP(true, 0),
    AGGRO_MULT(false, 0),
    ALL_DMG_AMP(false, 1),
    ALL_DMG_RES(false, 0),
    ALL_TYPE_RES_IGNORE(false, 0),
    ARMOR(false, 0),
    ARMOR_PEN(false, 0),
    ARROW_VELOCITY(false, 0),
    ATK(false, 0),
    ATK_COOLDOWN(false, 0),
    ATK_SIZE_AMP(false, 1),
    ATK_SPEED(false, 1),
    BLIGHT_DMG_AMP(false, 1),
    BLIGHT_DMG_RES(false, 1),
    CC_DEBUFF_EFFICIENCY(false, 1),
    CC_RES(false, 0),
    CHARGE(false, 0),
    CHARGE_MULT(false, 0),
    COMBO(true, 0),
    CRIT_DMG(false, 1.5),
    CRIT_RATE(false, 0),
    DASH_COOLDOWN(true, 150),
    DASH_COUNT(true, 1),
    DASH_LENGTH(false, 4),
    DECAY_DMG_AMP(false, 1),
    DECAY_DMG_RES(false, 0),
    DELAYED_DMG_AMP(false, 1),
    DELAYED_DMG_RES(false, 0),
    DIRECT_DMG_AMP(false, 1),
    DIRECT_DMG_RES(false, 0),
    DOT_AMP(false, 1),
    DOT_RES(false, 0),
    DROWNING_DMG_RES(false, 0),
    EARTH_DMG_AMP(false, 1),
    EARTH_DMG_RES(false, 0),
    ECHO_DMG_AMP(false, 1),
    ECHO_DMG_RES(false, 0),
    EFFECT_DURATION(false, 1),
    EFFECT_EFFICIENCY(false, 1),
    EFFECT_HIT_RATE(false, 0),
    EFFECT_RES(false, 0),
    ELEMENTAL_AFFINITY(false, 0),
    ELEMENTAL_MASTERY(false, 0),
    ENERGY_REGENERATION_RATE(false, 0),
    FALL_DMG_RES(false,0),
    FIRE_DMG_AMP(false, 1),
    FIRE_DMG_RES(false, 0),
    FOLLOW_UP_DMG_AMP(false, 1),
    FOLLOW_UP_DMG_RES(false, 0),
    GRAVITY_ACCELERATION(false, -0.08),
    HEALTH_REGENERATION_AMP(false, 0),
    ICE_DMG_AMP(false, 1),
    ICE_DMG_RES(false, 0),
    IMAGINARY_DMG_AMP(false, 1),
    IMAGINARY_DMG_RES(false, 0),
    INACCURACY(false, 0),
    INCOMING_HEALING_AMP(false, 1),
    INCOMING_SHIELD_STRENGTH_AMP(false, 1),
    INVULNERABLE_DURATION(true, 10),
    JUMP_STRENGTH(false, 1.25),
    KNOCKBACK_STRENGTH_AMP(false, 1),
    KNOCKBACK_RES (false, 0),
    LAVA_DMG_AMP(false,1),
    LAVA_DMG_RES(false, 0),
    LIFESTEAL(false, 0),
    LIGHTNING_DMG_AMP(false,1),
    LIGHTNING_DMG_RES(false,0),
    MACE_BLAST_RADIUS(false,1),
    MAGAZINE_CAPACITY(true,0),
    MANA_REGENERATION(false,0),
    MAX_BOND_OF_LIFE(false,2),
    MAX_COMBO(true,0),
    MAX_DRAW_DURATION(true,0),
    MAX_ENERGY(false,0),
    MAX_HEALTH(false,20),
    MAX_MANA(false, 0),
    MAX_ZOOM(false,1),
    MOVEMENT_SPEED(false, 2),
    NATURE_DMG_AMP(false,1),
    NATURE_DMG_RES(false,0),
    NON_DAMAGING_DEBUFF_EFFICIENCY(false,1),
    OUTGOING_HEALING_AMP(false,1),
    OUTGOING_SHIELD_STRENGTH_AMP(false, 1),
    PHYSICAL_DMG_AMP(false,1),
    PHYSICAL_DMG_RES(false,0),
    PRESERVE_AMMO_RATE(false,0),
    PROJECTILE_GRAVITY(false,0),
    REACH(false,0),
    REACTION_DMG_AMP(false, 1),
    REACTION_DMG_RES(false,0),
    RETALIATION_DMG_AMP(false,1),
    RETALIATION_DMG_RES(false,0),
    SELF_DMG_AMP(false,1),
    SUMMON_DMG_AMP(false,1),
    SUMMON_DMG_RES(false,0),
    SWEEP_ANGLE(false,1),
    VOID_DMG_AMP(false,1),
    VOID_DMG_RES(false,0),
    WATER_DMG_AMP(false,1),
    WATER_DMG_RES(false,0),
    WIND_DMG_AMP(false,1),
    WIND_DMG_RES(false,0),
    XP_GAIN(false,1);


    private final Boolean shouldBeTruncated;
    private final double baseValue;

    StatType(Boolean shouldBeTruncated, double baseValue) {
        this.shouldBeTruncated = shouldBeTruncated;
        this.baseValue = baseValue;
    }

    public Boolean getShouldBeTruncated() {
        return shouldBeTruncated;
    }
    public double getBaseValue() {
        return baseValue;
    }
}
