package com.w1therx.adventurerfantasy.common.enums;


import com.w1therx.adventurerfantasy.AdventurerFantasy;
import net.minecraft.resources.ResourceLocation;

public enum StatType {
    ADDITIONAL_JUMP(true, 0, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/additional_jump.png"),
            "$int",
            "Jump++",
            "Additional Jumps: $int",
            "The player can perform up to int upward boosts while in midair. This value is reset upon landing."),
    AGGRO_MULT(false, 1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/aggro_mult.png"),
            "$percentage%",
            "Aggro Mult",
            "Aggro Multiplier: $percentage%",
            "The chance of being attacked by enemies is increased by $percentage%."),
    ALL_DMG_AMP(false, 1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/all_dmg_amp.png"),
           "$percentage%",
            "Dmg Boost",
            "Damage Boost: $percentage%",
            "Damage dealt is multiplied by $percentage%."),
    ALL_DMG_RES(false, 0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/all_dmg_res.png"),
            "$percentage%",
            "Dmg Res",
            "Damage Resistance: $percentage%",
            "Decreases damage taken by $percentage%."),
    ALL_TYPE_RES_IGNORE(false, 0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/all_type_res_ignore.png"),
            "$percentage%",
            "All-Type Res Pen",
            "All-Type Resistance Penetration: $percentage%",
            "Enemies are considered of having $percentage% less damage resistance when attacked."),
    ARMOR(false, 0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/armor.png"),
            "$value",
            "Def",
            "Defense: $value",
            "The Defense's value is $value. All damage taken but DoT by 25% of this value and DoT by 5% of this value."),
    ARMOR_PEN(false, 0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/armor_pen.png"),
            "$percentage%",
            "Def Pen",
            "Defense Penetration: $percentage%",
            "Enemies are considered of having $percentage% less defense when attacked."),
    ARROW_VELOCITY(false, 0, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/arrow_velocity.png"),
            "$percentage%",
            "Velocity",
            "Projectile Velocity: $percentage%",
            "The projectiles' flying speed is $percentage% of their base value."),
    ATK(false, 0, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/atk.png"),
            "$value",
            "Atk",
            "Attack: $value",
            "The Attack's value is $value. It is usually used for damage calculations."),
    ATK_COOLDOWN(false, 0, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/atk_cooldown.png"),
            "$1/20 secs",
            "Atk Cooldown",
            "Attack Cooldown: $1/20 seconds",
            "The minimum interval between two consecutive attacks is $1/20 seconds. Its final value is divided by Attack Speed."),
    ATK_SIZE_AMP(false, 1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/atk_size_amp.png"),
            "$percentage%",
            "AoE Boost",
            "Attack Size Boost: $percentage%",
            "The area of attacks (excluding conic areas) is increased by $percentage%."),
    ATK_SPEED(false, 1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/atk_speed.png"),
            "$percentage%",
            "Atk Speed",
            "Attack Speed: $percentage%",
            "The Attack Speed's value is $percentage%. The quotient of Attack Cooldown and this value is the final Attack Cooldown value."),
    BLIGHT_DMG_AMP(false, 1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/blight_dmg_amp.png"),
            "$percentage%",
            "Blight Dmg Boost",
            "Blight Damage Boost",
            "Blight damage dealt is multiplied by $percentage%."),
    BLIGHT_DMG_RES(false, 0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/blight_dmg_res.png"),
            "$percentage%",
            "Blight Dmg Res",
            "Blight Damage Resistance: $percentage%",
            "Decreases Blight damage taken by $percentage%."),
    CC_DEBUFF_EFFICIENCY(false, 1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/cc_debuff_efficiency.png"),
            "$percentage%",
            "CC Efficiency",
            "Crowd Control Debuff Efficiency: $percentage%",
            "The efficiency of Crowd Control debuffs is multiplied by $percentage%."),
    CC_RES(false, 0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/cc_res.png"),
            "$percentage%",
            "CC Res",
            "Crowd Control Debuff Resistance: $percentage%",
            "Increases the chance to resist the application of crowd control debuffs by $percentage%."),
    CRIT_DMG(false, 1.5, 1, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/crit_dmg.png"),
            "$percentage%",
            "Crit Dmg",
            "Critical Strike Damage: $percentage%",
            "The damage dealt by critical strikes is multiplied by $percentage%."),
    CRIT_RATE(false, 0, 0, 1,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/crit_rate.png"),
            "$percentage%",
            "Crit Rate",
            "Critical Strike Rate: $percentage%",
            "Attacks have a $percentage% chance of being critical. Under normal circumstances DoT cannot trigger critical strikes."),
    DASH_COOLDOWN(true, 150, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/dash_cooldown.png"),
            "$1/20 secs",
            "Dash Cooldown",
            "Dash Cooldown: $1/20 seconds",
            "The minimum amount of time needed to recharge a dash is $1/20 seconds."),
    DASH_LENGTH(false, 4, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/dash_length.png"),
            "$valuem",
            "Dash Length",
            "Dash Length: $valuem",
            "The length of a dash on most terrains is $valuem."),
    DECAY_DMG_AMP(false, 1, 0,Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/decay_dmg_amp.png"),
            "$percentage%",
            "Decay Dmg Boost",
            "Decay Damage Boost: $percentage%",
            "Decay damage dealt is multiplied by $percentage%."),
    DECAY_DMG_RES(false, 0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/decay_dmg_res.png"),
            "$percentage%",
            "Decay Dmg Res",
            "Decay Damage Resistance: $percentage%",
            "Decay damage taken is decreased by $percentage%."),
    DELAYED_DMG_AMP(false, 1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/delayed_dmg_amp.png"),
            "$percentage%",
            "Delayed Dmg Boost",
            "Delayed Damage Boost: $percentage%",
            "Delayed damage dealt is multiplied by $percentage%."),
    DELAYED_DMG_RES(false, 0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/delayed_dmg_res.png"),
            "$percentage%",
            "Delayed Dmg Res",
            "Delayed Damage Resistance: $percentage%",
            "Delayed damage taken is decreased by $percentage%."),
    DIRECT_DMG_AMP(false, 1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/direct_dmg_amp.png"),
            "$percentage%",
            "Direct Dmg Boost",
            "Direct Damage Boost: $percentage%",
            "Direct damage dealt is multiplied by $percentage%."),
    DIRECT_DMG_RES(false, 0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/direct_dmg_res.png"),
            "$percentage%",
            "Direct Dmg Res",
            "Direct Damage Resistance: $percentage%",
            "Direct damage taken is decreased by $percentage%."),
    DODGE_CHANCE(false, 0, 0, 1,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/dodge_chance.png"),
            "$percentage%",
            "Dodge Chance",
            "Dodge Chance: $percentage%",
            "When attacked there is a $percentage% chance to dodge the incoming attack. Attacks dodged dealt no damage and trigger iFrames."),
    DOT_AMP(false, 1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/dot_amp.png"),
            "$percentage%",
            "DoT Boost",
            "DoT Boost: $percentage%",
            "DoT dealt is multiplied by $percentage%."),
    DOT_DMG_SPEED(false, 1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/dot_dmg_speed.png"),
            "$percentage%",
            "DoT Dmg Speed",
            "DoT Damaging Speed: $percentage%.",
            "The interval between a DoT effect's instances of damage is divided by $percentage%."),
    DOT_RES(false, 0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/dot_res.png"),
            "$percentage%",
            "DoT Res",
            "DoT Resistance: $percentage%",
            "DoT taken is decreased by $percentage%."),
    DROWNING_DMG_RES(false, 0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/drowning_dmg_res.png"),
            "$percentage%",
            "Drowning Dmg Res",
            "Drowning Damage Resistance: $percentage%",
            "Drowning damage taken is decreased by $percentage%."),
    EARTH_DMG_AMP(false, 1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/earth_dmg_amp.png"),
            "$percentage%",
            "Earth Dmg Boost",
            "Earth Damage Boost: $percentage%",
            "Earth damage dealt is multiplied by $percentage%."),
    EARTH_DMG_RES(false, 0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/earth_dmg_res.png"),
            "$percentage%",
            "Earth Dmg Res",
            "Earth Damage Resistance: $percentage%",
            "Earth damage taken is decreased by $percentage%."),
    ECHO_DMG_AMP(false, 1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/echo_dmg_amp.png"),
            "$percentage%",
            "Echo Dmg Boost",
            "Echo Damage Boost: $percentage%",
            "Echo damage dealt is multiplied by $percentage%."),
    ECHO_DMG_RES(false, 0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/echo_dmg_res.png"),
            "$percentage%",
            "Echo Dmg Res",
            "Echo Damage Resistance: $percentage%",
            "Echo damage taken is decreased by $percentage%."),
    EFFECT_DURATION(false, 1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/effect_duration.png"),
            "$percentage%",
            "Effect Duration",
            "Effect Duration: $percentage%",
            "The duration of effects applied is multiplied by $percentage%."),
    EFFECT_EFFICIENCY(false, 1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/effect_efficiency.png"),
            "$percentage%",
            "Effect Efficiency",
            "Effect Efficiency: $percentage%",
            "The efficiency of effects applied is multiplied by $percentage%."),
    EFFECT_HIT_RATE(false, 0, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/effect_hit_rate.png"),
            "$percentage%",
            "EHR",
            "Effect Hit Rate: $percentage%",
            "The chance to apply effects is increased by $percentage%."),
    EFFECT_RES(false, 0, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/effect_res.png"),
            "$percentage%",
            "Effect Res",
            "Effect Resistance: $percentage%",
            "The chance to resist incoming debuffs is increased by $percentage%."),
    ELEMENTAL_AFFINITY(false, 0, 0, 1,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/elemental_affinity.png"),
            "$percentage%",
            "Elemental Affinity",
            "Elemental Affinity: $percentage%",
            "The current Elemental Affinity's value is $percentage%. The greater the affinity, the more powerful elemental reactions become. Elemental Affinity mostly affects the frequency and area of elemental reactions."),
    ELEMENTAL_MASTERY(false, 0, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/elemental_mastery.png"),
            "$value",
            "Elemental Mastery",
            "Elemental Mastery: $value",
            "The current Elemental Mastery's value is $value. The greater the mastery, the more powerful elemental reactions become. Elemental Mastery mostly affects aspects of reactions such as strength, damage and duration."),
    ENERGY_REGENERATION_RATE(false, 0, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/energy_regeneration_rate.png"),
            "$percentage%",
            "ERR",
            "Energy Regeneration Rate: $percentage%",
            "The amount of energy regenerated is multiplied by $percentage%."),
    FALL_DMG_RES(false,0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/fall_dmg_res.png"),
            "$percentage%",
            "Fall Dmg Res",
            "Fall Damage Resistance: $percentage%",
            "Fall damage taken is decreased by $percentage%."),
    FIRE_DMG_AMP(false, 1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/fire_dmg_amp.png"),
            "$percentage%",
            "Fire Dmg Boost",
            "Fire Damage Boost: $percentage%",
            "Fire damage dealt is multiplied by $percentage%."),
    FIRE_DMG_RES(false, 0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/fire_dmg_res.png"),
            "$percentage%",
            "Fire Dmg Res",
            "Fire Damage Resistance: $percentage%",
            "Fire damage taken is decreased by $percentage%."),
    FOLLOW_UP_DMG_AMP(false, 1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/follow_up_dmg_amp.png"),
            "$percentage%",
            "Follow-Up Dmg Boost",
            "Follow-Up Damage Boost: $percentage%",
            "Follow-Up damage dealt is multiplied by $percentage%."),
    FOLLOW_UP_DMG_RES(false, 0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/follow_up_dmg_res.png"),
            "$percentage%",
            "Follow-Up Dmg Res",
            "Follow-Up Damage Resistance: $percentage%",
            "Follow-Up damage taken is decreased by $percentage%."),
    HEALTH_REGENERATION_AMP(false, 0, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/health_regeneration_amp.png"),
            "$percentage%",
            "HP Regen Boost",
            "Health Regeneration Boost: $percentage%",
            "Health regeneration rate is multiplied by $percentage%."),
    HEALTH_RESTORATION_ON_DEATH_DEFIANCE(false, 0, 0, 1,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/health_restoration_on_death_defiance.png"),
            "$percentage%",
            "HP% Upon Death Defiance",
            "Health Percentage Upon Defying Death: $percentage%",
            "When defying death, health is restored to $percentage% of max health."),
    ICE_DMG_AMP(false, 1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/ice_dmg_amp.png"),
            "$percentage%",
            "Ice Dmg Boost",
            "Ice Damage Boost: $percentage%",
            "Ice damage dealt is multiplied by $percentage%."),
    ICE_DMG_RES(false, 0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/ice_dmg_res.png"),
            "$percentage%",
            "Ice Dmg Res",
            "Ice Damage Resistance: $percentage%",
            "Ice damage taken is decreased by $percentage%."),
    IMAGINARY_DMG_AMP(false, 1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/imaginary_dmg_amp.png"),
            "$percentage%",
            "Imaginary Dmg Boost",
            "Imaginary Damage Boost: $percentage%",
            "Imaginary damage dealt is multiplied by $percentage%."),
    IMAGINARY_DMG_RES(false, 0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/imaginary_dmg_res.png"),
            "$percentage%",
            "Imaginary Dmg Res",
            "Imaginary Damage Resistance: $percentage%",
            "Imaginary damage taken is decreased by $percentage%."),
    INACCURACY(false, 0, 0, 180,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/inaccuracy.png"),
            "$value°",
            "Inaccuracy",
            "Inaccuracy: $value°",
            "Projectiles thrown have a random angular offset equal or less than $value°."),
    INCOMING_HEALING_AMP(false, 1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/incoming_healing_amp.png"),
            "$percentage%",
            "In Healing Boost",
            "Incoming Healing Boost: $percentage%",
            "Incoming healing is multiplied by $percentage%."),
    INCOMING_SHIELD_STRENGTH_AMP(false, 1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/incoming_shield_strength_amp.png"),
            "$percentage%",
            "In Shield Boost",
            "Incoming Shield Strength Boost: $percentage%",
            "Incoming shields is multiplied by $percentage%."),
    INVULNERABLE_DURATION(true, 10, 1, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/invulnerable_duration.png"),
            "$1/20 secs",
            "IFrames Duration",
            "IFrames Duration: $1/20 secs",
            "After being attacked, a $1/20 secs invulnerability is triggered."),
    KNOCKBACK_STRENGTH_AMP(false, 1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/knockback_strength_amp.png"),
            "$percentage%",
            "Knockback Boost",
            "Knockback Strength Boost: $percentage%",
            "Knockback dealt with attacks is multiplied $percentage%.."),
    KNOCKBACK_RES (false, 0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/knockback_res.png"),
            "$percentage%",
            "Knockback Res",
            "Knockback Resistance: $percentage%",
            "Knockback taken is decreased by $percentage%."),
    LAVA_DMG_AMP(false,1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/lava_dmg_amp.png"),
            "$percentage%",
            "Lava Dmg Boost",
            "Lava Damage Boost: $percentage%",
            "Lava damage dealt is multiplied by $percentage%."),
    LAVA_DMG_RES(false, 0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/lava_dmg_res.png"),
            "$percentage%",
            "Lava Dmg Res",
            "Lava Damage Resistance: $percentage%",
            "Lava damage taken is decreased by $percentage%."),
    LIFESTEAL(false, 0, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/lifesteal.png"),
            "$percentage%",
            "Lifesteal",
            "Lifesteal: $percentage%",
            "When attacking, up to $percentage% damage dealt can be converted into healing."),
    LIGHTNING_DMG_AMP(false,1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/lightning_dmg_amp.png"),
            "$percentage%",
            "Lightning Dmg Boost",
            "Lightning Damage Boost: $percentage%",
            "Lightning damage dealt is multiplied by $percentage%."),
    LIGHTNING_DMG_RES(false,0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/lightning_dmg_res.png"),
            "$percentage%",
            "Lightning Dmg Res",
            "Lightning Damage Resistance: $percentage%",
            "Lightning damage taken is decreased by $percentage%."),
    MACE_BLAST_RADIUS(false,1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/mace_blast_radius.png"),
            "$valuem",
            "Mace Blast Radius",
            "Mace Blast Radius: $valuem",
            "Mace alternate attacks deal damage in a $valuem radius."),
    MAGAZINE_CAPACITY(true,0, 0, 6,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/magazine_capacity.png"),
            "$int",
            "Magazine Capacity",
            "Magazine Capacity: $int",
            "Up to $int ammo can be stored at once."),
    MANA_REGENERATION(false,0, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/mana_regeneration.png"),
            "$value/sec",
            "Mana Regen",
            "Mana Regeneration: $value/sec",
            "Each sec $value mana is regenerated."),
    MAX_BOND_OF_LIFE(false,2, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/max_bond_of_life.png"),
            "$value",
            "Max BoL",
            "Maximum Bond of Life: $value",
            "The maximum Bond of Life is $value."),
    MAX_COMBO(true,0, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/max_combo.png"),
            "$int",
            "Max Combo",
            "Maximum Combo: $int",
            "The maximum achievable number of combo is $int."),
    MAX_DASHES (true, 1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/dash_count.png"),
            "$int",
            "Max Dashes",
            "Maximum Dashes: $int",
            "The maximum amount of chances to perform a dash stored at the same time is $int."),
    MAX_DRAW_DURATION(true,0, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/max_draw_duration.png"),
            "$1/20 secs",
            "Max Draw Duration",
            "Maximum Draw Duration: $1/20 secs",
            "The maximum draw duration is $1/20 secs."),
    MAX_ENERGY(false,0, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/max_energy.png"),
            "$value",
            "Max Energy",
            "Maximum Energy: $value",
            "The energy needed to unleash Ultimates (if the circumstances allow) is $value."),
    MAX_HEALTH(false,0.1, 0.1, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/max_health.png"),
            "$value",
            "Max Health",
            "Maximum Health: $value",
            "The maximum health value is $value."),
    MAX_MANA(false, 0, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/max_mana.png"),
            "$value",
            "Max Mana",
            "Maximum Mana: $value",
            "The maximum Mana value is $value."),
    MAX_ZOOM(false,1, 1, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/max_zoom.png"),
            "$percentage%",
            "Max Zoom",
            "Maximum Zoom: $percentage%",
            "The camara's zoom can be increased up to $percentage%."),
    MINING_SPEED(false, 1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/mining_speed.png"),
            "$percentage%",
            "Mining Speed",
            "Mining Speed: $percentage%",
            "The actual mining speed is multiplied by $percentage%."),
    MOVEMENT_SPEED(false, 2, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/movement_speed.png"),
            "$value m/sec",
            "Move Speed",
            "Movement Speed: $value m/sec",
            "The speed at which you are moving is $value m/sec."),
    NATURE_DMG_AMP(false,1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/nature_dmg_amp.png"),
            "$percentage%",
            "Nature Dmg Boost",
            "Nature Damage Boost: $percentage%",
            "Nature damage dealt is multiplied by $percentage%."),
    NATURE_DMG_RES(false,0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/nature_dmg_res.png"),
            "$percentage%",
            "Nature Dmg Res",
            "Nature Damage Resistance: $percentage%",
            "Nature damage taken is decreased by $percentage%."),
    NON_DAMAGING_DEBUFF_EFFICIENCY(false,1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/non_damaging_debuff_efficiency.png"),
            "$percentage%",
            "Non-Damaging Debuff Boost",
            "Non-Damaging Debuff Boost: $percentage%",
            "The efficiency of debuffs that don't deal damage is multiplied by $percentage%."),
    OUTGOING_HEALING_AMP(false,1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/outgoing_healing_amp.png"),
            "$percentage%",
            "Out Healing Boost",
            "Outgoing Healing Boost: $percentage%",
            "Outgoing healing is multiplied by $percentage%."),
    OUTGOING_SHIELD_STRENGTH_AMP(false, 1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/outgoing_shield_strength_amp.png"),
            "$percentage%",
            "Out Shield Boost",
            "Outgoing Shield Strength Boost: $percentage%",
            "Outgoing shields' strength is multiplied by $percentage%."),
    PHYSICAL_DMG_AMP(false,1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/physical_dmg_amp.png"),
            "$percentage%",
            "Physical Dmg Boost",
            "Physical Damage Boost: $percentage%",
            "Physical damage dealt is multiplied by $percentage%."),
    PHYSICAL_DMG_RES(false,0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/physical_dmg_res.png"),
            "$percentage%",
            "Physical Dmg Res",
            "Physical Damage Resistance: $percentage%",
            "Physical damage taken is decreased by $percentage%."),
    PRESERVE_AMMO_RATE(false,0, 0, 1,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/preserve_ammo_rate.png"),
            "$percentage%",
            "Preserve Ammo Rate",
            "Preserve Ammo Rate: $percentage%",
            "When firing a non-magical projectile, there is a $percentage% chance not to consume ammo."),
    PROJECTILE_GRAVITY(false,0, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/projectile_gravity.png"),
            "$percentage%",
            "Projectile Gravity",
            "Projectile Gravity: $percentage%",
            "The projectiles' gravitational pull is multiplied by $percentage%."),
    REACH(false,0, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/reach.png"),
            "$valuem",
            "Reach",
            "Reach: $valuem",
            "Conic basic attacks have a $valuem reach."),
    REACTION_DMG_AMP(false, 1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/reaction_dmg_amp.png"),
            "$percentage%",
            "Reaction Dmg Boost",
            "Reaction Damage Boost: $percentage%",
            "Reaction damage dealt is multiplied by $percentage%."),
    REACTION_DMG_RES(false,0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/reaction_dmg_res.png"),
            "$percentage%",
            "Reaction Dmg Res",
            "Reaction Damage Resistance: $percentage%",
            "Reaction damage taken is decreased by $percentage%."),
    RETALIATION_DMG_AMP(false,1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/retaliation_dmg_amp.png"),
            "$percentage%",
            "Retaliation Dmg Boost",
            "Retaliation Damage Boost: $percentage%",
            "Retaliation damage dealt is multiplied by $percentage%."),
    RETALIATION_DMG_RES(false,0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/retaliation_dmg_res.png"),
            "$percentage%",
            "Retaliation Dmg Res",
            "Retaliation Damage Res: $percentage%",
            "Retaliation damage taken is decreased  by $percentage%."),
    SELF_DMG_AMP(false,1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/self_dmg_amp.png"),
            "$percentage%",
            "Self-Dmg Boost",
            "Self-Inflicted Damage Boost: $percentage%",
            "Self-Inflicted damage is multiplied by $percentage%."),
    SUMMON_DMG_AMP(false,1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/summon_dmg_amp.png"),
            "$percentage%",
            "Summon Dmg Boost",
            "Summon Damage Boost: $percentage%",
            "Summon damage dealt is multiplied by $percentage%."),
    SUMMON_DMG_RES(false,0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/summon_dmg_res.png"),
            "$percentage%",
            "Summon Dmg Res",
            "Summon Damage Resistance: $percentage%",
            "Summon damage taken is decreased by $percentage%."),
    SWEEP_ANGLE(false,0, 0, 360,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/sweep_angle.png"),
            "$value°",
            "Sweep Angle",
            "Sweep Angle: $value°",
            "Basic conic attacks' angular width is $value°."),
    ULTIMATE_DMG_AMP (false, 1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/ultimate_dmg_amp.png"),
            "$percentage%",
            "Ultimate Dmg Boost",
            "Ultimate Damage Boost: $percentage%",
            "Ultimate damage dealt is multiplied by $percentage%."),
    ULTIMATE_DMG_RES(false, 0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/ultimate_dmg_res.png"),
            "$percentage%",
            "Ultimate Dmg Res",
            "Ultimate Damage Resistance: $percentage%",
            "Ultimate damage taken is decreased by $percentage%."),
    VOID_DMG_AMP(false,1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/void_dmg_amp.png"),
            "$percentage%",
            "Void Dmg Boost",
            "Void Damage Boost: $percentage%",
            "Void damage dealt is multiplied by $percentage%."),
    VOID_DMG_RES(false,0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/void_dmg_res.png"),
            "$percentage%",
            "Void Dmg Res",
            "Void Damage Resistance: $percentage%",
            "Void damage taken is decreased by $percentage%."),
    WATER_DMG_AMP(false,1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/water_dmg_amp.png"),
            "$percentage%",
            "Water Dmg Boost",
            "Water Dmg Boost: $percentage%",
            "Water damage dealt is multiplied by $percentage%."),
    WATER_DMG_RES(false,0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/water_dmg_res.png"),
            "$percentage%",
            "Water Dmg Res",
            "Water Damage Resistance: $percentage%",
            "Water damage taken is decreased by $percentage%."),
    WIND_DMG_AMP(false,1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/wind_dmg_amp.png"),
            "$percentage%",
            "Wind Dmg Boost",
            "Wind Damage Boost: $percentage%",
            "Wind damage dealt is increased by $percentage%."),
    WIND_DMG_RES(false,0, -Double.MAX_VALUE, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/wind_dmg_res.png"),
            "$percentage%",
            "Wind Dmg Res",
            "Wind Damage Resistance: $percentage%",
            "Wind damage taken is decreased by $percentage%."),
    XP_GAIN(false,1, 0, Double.MAX_VALUE,
            ResourceLocation.fromNamespaceAndPath(AdventurerFantasy.MOD_ID, "textures/gui/xp_gain.png"),
            "$percentage%",
            "XP Gain",
            "XP Gain: $percentage%",
            "Experience gained by killing enemies is multiplied by $percentage%.");


    private final Boolean shouldBeTruncated;
    private final double baseValue;
    private final double minValue;
    private final double maxValue;
    private final ResourceLocation icon;
    private final String value;
    private final String shortName;
    private final String name;
    private final String description;

    StatType(Boolean shouldBeTruncated, double baseValue, double minValue, double maxValue, ResourceLocation icon, String value, String shortName, String name, String description) {
        this.shouldBeTruncated = shouldBeTruncated;
        this.baseValue = baseValue;
        this.minValue = minValue;
        this.maxValue = maxValue;
        this.icon = icon;
        this.value = value;
        this.name = name;
        this.description = description;
        this.shortName = shortName;
    }

    public Boolean getShouldBeTruncated() {
        return shouldBeTruncated;
    }
    public double getBaseValue() {
        return baseValue;
    }
    public double getMinValue() { return minValue; }
    public double getMaxValue() { return maxValue; }
    public ResourceLocation getIcon() { return icon; }
    public String getValue() {return value; }
    public String getShortName() { return shortName; }
    public String getName() { return name; }
    public String getDescription() { return description;}
}
